version: "3"
services:
  test:
    build: .
    ports:
      - "3600"
    container_name: gfw-fires-api-test
    environment:
      NODE_ENV: test
      PORT: 3600
      NODE_PATH: app/src
      CT_URL: http://mymachine:9000
      LOCAL_URL: http://127.0.0.1:3600
      CT_REGISTER_MODE: auto
      API_VERSION: v1
      CT_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.IRCIRm1nfIQTfda_Wb6Pg-341zhV8soAgzw7dd5HxxQ
      FASTLY_ENABLED: "false"
    command: test
