version: "3"
services:
  develop:
    build: .
    ports:
      - "3700:3600"
    container_name: gfw-fires-api-develop
    environment:
      PORT: 3600
      NODE_PATH: app/src
      NODE_ENV: dev
      CARTODB_USER: wri-01
      CT_URL: http://mymachine:9000
      LOCAL_URL: http://mymachine:3700
      CT_REGISTER_MODE: auto
      API_VERSION: v1
    command: develop
    volumes:
      - ./app:/opt/gfw-viirs-fires-api/app
