develop:
  extends:
    file: base.yml
    service: base
  container_name: gfw-fires-api-develop
  environment:
    NODE_ENV: dev
    CARTODB_USER: wri-01
    API_GATEWAY_URL: http://mymachine:9000
    API_VERSION: v1
  command: develop
  volumes:
    - ./app:/opt/gfw-viirs-fires-api/app
