develop:
  extends:
    file: base.yml
    service: base
  container_name: gfw-fires-api-develop
  environment:
    NODE_ENV: dev
    CARTODB_APIKEY: <apikey>
    CARTODB_USER: <user>
  command: develop
  volumes:
    - ./app:/opt/gfw-viirs-fires-api/app
