develop:
  extends:
    file: base.yml
    service: base
  container_name: gfw-fires-api-develop
  environment:
    NODE_ENV: dev
    CARTODB_USER: wri-01
  command: start
  volumes:
    - ./app:/opt/gfw-viirs-fires-api/app
