version: "3"
services:
  develop:
    build: .
    ports:
      - "3700:3600"
    container_name: gfw-fires-api-develop
    environment:
      PORT: 3600
      NODE_PATH: app/src
      NODE_ENV: dev
      CT_URL: http://mymachine:9000
      LOCAL_URL: http://mymachine:3700
      CT_REGISTER_MODE: auto
      API_VERSION: v1
      CT_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.IRCIRm1nfIQTfda_Wb6Pg-341zhV8soAgzw7dd5HxxQ
      FASTLY_ENABLED: "false"
    command: develop
    volumes:
      - ./app:/opt/gfw-viirs-fires-api/app
