apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: gfw
  labels:
    name: viirs-fires
  name: viirs-fires
spec:
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        name: viirs-fires
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - apps
      containers:
      - name: viirs-fires
        image: vizzuality/viirs-fires
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "0.25"
            memory: "256M"
          limits:
            cpu: "1"
            memory: "512M"
        args:
          - start
        env:
          - name: PORT
            value: "3600"
          - name: NODE_ENV
            value: prod
          - name: NODE_PATH
            value: app/src
          - name: LOCAL_URL
            value: http://viirs-fires.gfw.svc.cluster.local:3600
          - name: CT_URL
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_URL
          - name: CT_TOKEN
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_TOKEN
          - name: CT_REGISTER_MODE
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_REGISTER_MODE
          - name: API_VERSION
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: API_VERSION
          - name: DATASETS_URI
            value: https://production-api.globalforestwatch.org
          - name: VIIRS_GADM_DAILY_DATASET_ID
            value: 875863d1-35bb-44f2-8b71-03beb5c90c38
          - name: VIIRS_GADM_ALL_DATASET_ID
            value: a2475f80-e48b-455d-b8d1-198bd6b8e91d
          - name: GADM_SUMMARY_ID
            value: debb1526-4994-4c3b-9304-e536d1cde694
          - name: VIIRS_WDPA_DAILY_DATASET_ID
            value: 43371354-4a60-4cac-afd9-1e4627682ea2
          - name: WDPA_SUMMARY_ID
            value: 5ca5434d-17b3-427b-b540-612189da61e7
        ports:
          - containerPort: 3600
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /healthcheck
            port: 3600
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 15
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /healthcheck
            port: 3600
          failureThreshold: 3
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 15

      restartPolicy: Always
